import{S as m,i as c}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();function d(s){const n=`https://pixabay.com/api/?${new URLSearchParams({key:"43104791-fccc42375971f64c47e678deb",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(n).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()})}const h=document.querySelector(".gallery");function y(s){const o=s.map(({largeImageURL:r,webformatURL:e,tags:t,likes:i,views:u,comments:p,downloads:f})=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${r}">
        <img class="photo" src="${e}" alt="${t}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${i}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${u}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${p}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${f}</p></li>
        </ul>
        </li>`).join("");h.insertAdjacentHTML("beforeend",o),new m(".gallery a",{captionsData:"alt"}).refresh()}const g=document.querySelector(".gallery");let a;const L=document.querySelector("input"),b=document.querySelector("form"),l=document.querySelector(".loader");function w(){l.classList.remove("is-hidden")}function S(){l.classList.add("is-hidden")}b.addEventListener("submit",q);function q(s){if(s.preventDefault(),g.innerHTML="",a=L.value.trim(),w(),a===""){c.show({color:"yellow",message:"Please fill in the field for search!",position:"topRight"});return}d(a).then(o=>y(o.hits)).catch(o=>{console.log(o),c.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})}).finally(()=>S()),s.target.reset()}
//# sourceMappingURL=commonHelpers.js.map
