import{S as m,i as a}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();function h(s){const n=`https://pixabay.com/api/?${new URLSearchParams({key:"43104791-fccc42375971f64c47e678deb",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(n).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})}const d=document.querySelector(".gallery");function g(s){const r=s.map(({largeImageURL:o,webformatURL:e,tags:t,likes:i,views:u,comments:p,downloads:f})=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${o}">
        <img class="photo" src="${e}" alt="${t}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${i}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${u}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${p}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${f}</p></li>
        </ul>
        </li>`).join("");d.insertAdjacentHTML("beforeend",r),new m(".gallery a",{captionsData:"alt"}).refresh()}const y=document.querySelector(".gallery");let c;const L=document.querySelector("input"),b=document.querySelector("form"),l=document.querySelector(".loader");function S(){l.classList.remove("is-hidden")}function q(){l.classList.add("is-hidden")}b.addEventListener("submit",w);function w(s){if(s.preventDefault(),y.innerHTML="",c=L.value.trim(),S(),c===""){a.error({color:"yellow",message:"Please fill in the field for search!",position:"topRight"});return}if(data.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"red",messageColor:"white",position:"topRight"});return}else h(c).then(r=>g(r.hits)).catch(r=>{console.log(r),a.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})}).finally(()=>q());s.target.reset()}
//# sourceMappingURL=commonHelpers.js.map
